//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IGamePlatformsClient {

    getAll(): Promise<GamePlatformEntity[]>;
}

export class GamePlatformsClient implements IGamePlatformsClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getAll(): Promise<GamePlatformEntity[]> {
        let url_ = this.baseUrl + "/GamePlatforms";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAll(_response);
        });
    }

    protected processGetAll(response: Response): Promise<GamePlatformEntity[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(GamePlatformEntity.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GamePlatformEntity[]>(null as any);
    }
}

export interface IGamesClient {

    getAllGames(platformId: number): Promise<BasicGameInfoDto[]>;

    getGameImages(gameId: number): Promise<GameImageDto[]>;

    getGameLocations(platformId: number): Promise<PlatformLocationDto[]>;

    setGameLocation(gameId: number, locationId: number): Promise<number>;

    updateGameInfo(game: BasicGameInfoDto): Promise<BasicGameInfoDto>;
}

export class GamesClient implements IGamesClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getAllGames(platformId: number): Promise<BasicGameInfoDto[]> {
        let url_ = this.baseUrl + "/Games/{platformId}";
        if (platformId === undefined || platformId === null)
            throw new Error("The parameter 'platformId' must be defined.");
        url_ = url_.replace("{platformId}", encodeURIComponent("" + platformId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAllGames(_response);
        });
    }

    protected processGetAllGames(response: Response): Promise<BasicGameInfoDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(BasicGameInfoDto.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BasicGameInfoDto[]>(null as any);
    }

    getGameImages(gameId: number): Promise<GameImageDto[]> {
        let url_ = this.baseUrl + "/Games/images/{gameId}";
        if (gameId === undefined || gameId === null)
            throw new Error("The parameter 'gameId' must be defined.");
        url_ = url_.replace("{gameId}", encodeURIComponent("" + gameId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetGameImages(_response);
        });
    }

    protected processGetGameImages(response: Response): Promise<GameImageDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(GameImageDto.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GameImageDto[]>(null as any);
    }

    getGameLocations(platformId: number): Promise<PlatformLocationDto[]> {
        let url_ = this.baseUrl + "/Games/locations/{platformId}";
        if (platformId === undefined || platformId === null)
            throw new Error("The parameter 'platformId' must be defined.");
        url_ = url_.replace("{platformId}", encodeURIComponent("" + platformId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetGameLocations(_response);
        });
    }

    protected processGetGameLocations(response: Response): Promise<PlatformLocationDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(PlatformLocationDto.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PlatformLocationDto[]>(null as any);
    }

    setGameLocation(gameId: number, locationId: number): Promise<number> {
        let url_ = this.baseUrl + "/Games/set-location/{gameId}/{locationId}";
        if (gameId === undefined || gameId === null)
            throw new Error("The parameter 'gameId' must be defined.");
        url_ = url_.replace("{gameId}", encodeURIComponent("" + gameId));
        if (locationId === undefined || locationId === null)
            throw new Error("The parameter 'locationId' must be defined.");
        url_ = url_.replace("{locationId}", encodeURIComponent("" + locationId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "PUT",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSetGameLocation(_response);
        });
    }

    protected processSetGameLocation(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(null as any);
    }

    updateGameInfo(game: BasicGameInfoDto): Promise<BasicGameInfoDto> {
        let url_ = this.baseUrl + "/Games/update";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(game);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateGameInfo(_response);
        });
    }

    protected processUpdateGameInfo(response: Response): Promise<BasicGameInfoDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = BasicGameInfoDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BasicGameInfoDto>(null as any);
    }
}

export interface IImageClient {

    getImage(platform: string, gameId: number): Promise<FileResponse | null>;
}

export class ImageClient implements IImageClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getImage(platform: string, gameId: number): Promise<FileResponse | null> {
        let url_ = this.baseUrl + "/Image/game/{platform}/{gameId}";
        if (platform === undefined || platform === null)
            throw new Error("The parameter 'platform' must be defined.");
        url_ = url_.replace("{platform}", encodeURIComponent("" + platform));
        if (gameId === undefined || gameId === null)
            throw new Error("The parameter 'gameId' must be defined.");
        url_ = url_.replace("{gameId}", encodeURIComponent("" + gameId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetImage(_response);
        });
    }

    protected processGetImage(response: Response): Promise<FileResponse | null> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse | null>(null as any);
    }
}

export interface IReceiptClient {

    getOrderInformation(receiptId: number): Promise<GameReceiptDto>;

    updateReceipt(receipt: GameReceiptDto): Promise<GameReceiptDto>;
}

export class ReceiptClient implements IReceiptClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getOrderInformation(receiptId: number): Promise<GameReceiptDto> {
        let url_ = this.baseUrl + "/Receipt/order-info/{receiptId}";
        if (receiptId === undefined || receiptId === null)
            throw new Error("The parameter 'receiptId' must be defined.");
        url_ = url_.replace("{receiptId}", encodeURIComponent("" + receiptId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetOrderInformation(_response);
        });
    }

    protected processGetOrderInformation(response: Response): Promise<GameReceiptDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GameReceiptDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GameReceiptDto>(null as any);
    }

    updateReceipt(receipt: GameReceiptDto): Promise<GameReceiptDto> {
        let url_ = this.baseUrl + "/Receipt/update";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(receipt);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateReceipt(_response);
        });
    }

    protected processUpdateReceipt(response: Response): Promise<GameReceiptDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GameReceiptDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GameReceiptDto>(null as any);
    }
}

export class GamePlatformEntity implements IGamePlatformEntity {
    platformID!: number;
    platformName!: string;

    constructor(data?: IGamePlatformEntity) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.platformID = _data["platformID"];
            this.platformName = _data["platformName"];
        }
    }

    static fromJS(data: any): GamePlatformEntity {
        data = typeof data === 'object' ? data : {};
        let result = new GamePlatformEntity();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["platformID"] = this.platformID;
        data["platformName"] = this.platformName;
        return data;
    }
}

export interface IGamePlatformEntity {
    platformID: number;
    platformName: string;
}

export class BasicGameInfoDto implements IBasicGameInfoDto {
    gameID!: number;
    gameName!: string;
    platformID!: number;
    locationID!: number;
    gameCaseLocation!: string;
    hasGameBox!: boolean;
    gameRating!: number;
    imagePath!: string;
    locationName!: string;
    platformName!: string;
    hasProtection!: boolean;
    store!: string;
    receiptNumber!: string;
    gamePrice!: number;
    receiptDate?: Date | undefined;
    gameSold!: boolean;
    haveReceipt!: boolean;
    receiptName!: string;
    receiptScanned!: boolean;
    receiptID!: number;

    constructor(data?: IBasicGameInfoDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.gameID = _data["gameID"];
            this.gameName = _data["gameName"];
            this.platformID = _data["platformID"];
            this.locationID = _data["locationID"];
            this.gameCaseLocation = _data["gameCaseLocation"];
            this.hasGameBox = _data["hasGameBox"];
            this.gameRating = _data["gameRating"];
            this.imagePath = _data["imagePath"];
            this.locationName = _data["locationName"];
            this.platformName = _data["platformName"];
            this.hasProtection = _data["hasProtection"];
            this.store = _data["store"];
            this.receiptNumber = _data["receiptNumber"];
            this.gamePrice = _data["gamePrice"];
            this.receiptDate = _data["receiptDate"] ? new Date(_data["receiptDate"].toString()) : <any>undefined;
            this.gameSold = _data["gameSold"];
            this.haveReceipt = _data["haveReceipt"];
            this.receiptName = _data["receiptName"];
            this.receiptScanned = _data["receiptScanned"];
            this.receiptID = _data["receiptID"];
        }
    }

    static fromJS(data: any): BasicGameInfoDto {
        data = typeof data === 'object' ? data : {};
        let result = new BasicGameInfoDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["gameID"] = this.gameID;
        data["gameName"] = this.gameName;
        data["platformID"] = this.platformID;
        data["locationID"] = this.locationID;
        data["gameCaseLocation"] = this.gameCaseLocation;
        data["hasGameBox"] = this.hasGameBox;
        data["gameRating"] = this.gameRating;
        data["imagePath"] = this.imagePath;
        data["locationName"] = this.locationName;
        data["platformName"] = this.platformName;
        data["hasProtection"] = this.hasProtection;
        data["store"] = this.store;
        data["receiptNumber"] = this.receiptNumber;
        data["gamePrice"] = this.gamePrice;
        data["receiptDate"] = this.receiptDate ? this.receiptDate.toISOString() : <any>undefined;
        data["gameSold"] = this.gameSold;
        data["haveReceipt"] = this.haveReceipt;
        data["receiptName"] = this.receiptName;
        data["receiptScanned"] = this.receiptScanned;
        data["receiptID"] = this.receiptID;
        return data;
    }
}

export interface IBasicGameInfoDto {
    gameID: number;
    gameName: string;
    platformID: number;
    locationID: number;
    gameCaseLocation: string;
    hasGameBox: boolean;
    gameRating: number;
    imagePath: string;
    locationName: string;
    platformName: string;
    hasProtection: boolean;
    store: string;
    receiptNumber: string;
    gamePrice: number;
    receiptDate?: Date | undefined;
    gameSold: boolean;
    haveReceipt: boolean;
    receiptName: string;
    receiptScanned: boolean;
    receiptID: number;
}

export class GameImageDto implements IGameImageDto {
    gameID!: number;
    imageType!: string;
    imageOrder!: number;
    imagePath!: string;

    constructor(data?: IGameImageDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.gameID = _data["gameID"];
            this.imageType = _data["imageType"];
            this.imageOrder = _data["imageOrder"];
            this.imagePath = _data["imagePath"];
        }
    }

    static fromJS(data: any): GameImageDto {
        data = typeof data === 'object' ? data : {};
        let result = new GameImageDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["gameID"] = this.gameID;
        data["imageType"] = this.imageType;
        data["imageOrder"] = this.imageOrder;
        data["imagePath"] = this.imagePath;
        return data;
    }
}

export interface IGameImageDto {
    gameID: number;
    imageType: string;
    imageOrder: number;
    imagePath: string;
}

export class PlatformLocationDto implements IPlatformLocationDto {
    platformLocationID!: number;
    platformID!: number;
    locationName!: string;

    constructor(data?: IPlatformLocationDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.platformLocationID = _data["platformLocationID"];
            this.platformID = _data["platformID"];
            this.locationName = _data["locationName"];
        }
    }

    static fromJS(data: any): PlatformLocationDto {
        data = typeof data === 'object' ? data : {};
        let result = new PlatformLocationDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["platformLocationID"] = this.platformLocationID;
        data["platformID"] = this.platformID;
        data["locationName"] = this.locationName;
        return data;
    }
}

export interface IPlatformLocationDto {
    platformLocationID: number;
    platformID: number;
    locationName: string;
}

export class GameReceiptDto implements IGameReceiptDto {
    receiptID!: number;
    store!: string;
    receiptNumber!: string;
    receiptDate!: Date;
    receiptName!: string;
    receiptUrl!: string;
    receiptScanned!: boolean;

    constructor(data?: IGameReceiptDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.receiptID = _data["receiptID"];
            this.store = _data["store"];
            this.receiptNumber = _data["receiptNumber"];
            this.receiptDate = _data["receiptDate"] ? new Date(_data["receiptDate"].toString()) : <any>undefined;
            this.receiptName = _data["receiptName"];
            this.receiptUrl = _data["receiptUrl"];
            this.receiptScanned = _data["receiptScanned"];
        }
    }

    static fromJS(data: any): GameReceiptDto {
        data = typeof data === 'object' ? data : {};
        let result = new GameReceiptDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["receiptID"] = this.receiptID;
        data["store"] = this.store;
        data["receiptNumber"] = this.receiptNumber;
        data["receiptDate"] = this.receiptDate ? this.receiptDate.toISOString() : <any>undefined;
        data["receiptName"] = this.receiptName;
        data["receiptUrl"] = this.receiptUrl;
        data["receiptScanned"] = this.receiptScanned;
        return data;
    }
}

export interface IGameReceiptDto {
    receiptID: number;
    store: string;
    receiptNumber: string;
    receiptDate: Date;
    receiptName: string;
    receiptUrl: string;
    receiptScanned: boolean;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    throw new ApiException(message, status, response, headers, result);
}