CREATE TABLE `Games` (
	`GameId` INT(11) NOT NULL AUTO_INCREMENT,
	`GameName` VARCHAR(256) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`GameId`) USING BTREE
) COLLATE = 'utf8mb4_general_ci' ENGINE = InnoDB;